### PR TITLE
Create Molex 46765 family

### PR DESCRIPTION
**Pull request by evanshultz**
Fix of https://github.com/KiCad/Connectors_Molex.pretty/pull/9, plus adding the other family parts.

Datasheet http://www.molex.com/pdm_docs/sd/467651301_sd.pdf (it can be a bit confusing because the part drawings and recommended footprints don't use the MPNs)

Looking at the [Molex family page](http://www.molex.com/molex/products/listview.jsp?query=46765&path=46765+inmeta:promotable%3Dyes+inmeta:CollectionName%3DImpulse+inmeta:category%3DI%252FO%2520Connectors%26requiredfields=(engineeringnumber:46765%7Coldpartnumber:46765%7Cproductseries:46765)&offset=0&autoNav=0&sType=a&filter=&fs=&channel=products&encode=true), there are three footprints which I'll name as follows:
- `HDMI_Micro-D_Molex_46765-0x01`: 467650001, 467650301: SMD
- `HDMI_Micro-D_Molex_46765-1x01`: 467651001, 467651301: THT
- `HDMI_Micro-D_Molex_46765-2x0x`: 467652001, 467652301, 467652302: hybrid THT/SMD

### CODE REVIEW

**Comment by evanshultz** [comment]
Notes for all footprints:
- Footprint origin will match the datasheet origin for easiest checking.
- Keepout area is marked in the lame fashion which is the best we can do currently.
- There is no symbol in the library for an HDMI connector that I can see, so I have nothing against which to check the pinout.

**Comment by evanshultz** [comment]
`HDMI_Micro-D_Molex_46765-0x01` changes from old PR above:
- Renamed footprint.
- Added description and tags.
- Set SMD attribute since several USB connectors with SMD pins but THT mtg holes have this attribute.
- Added 3D model.
- Fixed all line widths, moved silk to fit and avoid pads, move courtyard to proper location.
- Added ref des on F.Fab.
- Fixed odd number pins to be 0.23x0.85mm (height was 0.86mm) and moved them to the correct Y location of 6.475mm (6.05mm + 0.85mm / 2).
- Changed keepout zone from a copper pad to F.Fab lines.
- Changed board edge line from F.Fab to Dwgs.User as on some USB connectors.

Image:
image

**Comment by evanshultz** [comment]
Ready for review. Image of all 3 footprints above. Thanks!

**Comment by evanshultz** [comment]
@SchrodingersGat Why stop now? How about this one?

I saw in another PR (can't find it now) you mentioned that the origin doesn't have to be in the center if that makes comparing dimensions to the datasheet easier. So I did it here. If that's not OK, please advise.

Also, there's not much room with this keepout style to place the F.Fab refdes and give it nice fat 0.15mm thick text lines. Do you see a better way?

**Comment by SchrodingersGat** [comment]
1. Sorry I'm out of time right now :)
1. The origin can be moved not to "make comparing dimensions easier", but if the datasheet explicitly places the origin somewhere other than the pad centres (i.e. the pick-and-place origin for machine loading)
1. Looks like the large RefDes would fit on top of the pads OK :)

**Comment by evanshultz** [comment]
@SchrodingersGat 
F.Fab refdes moved and enlarged.

Indeed, I did place the origin where it is on the datasheet. Which makes comparing dimensions between the datasheet and the footprint easier.

**Comment by evanshultz** [comment]
@SchrodingersGat Is this good? Reminder that we can enable this .pretty repo once these footprints are merged.

**Comment by SchrodingersGat** [comment]
@evanshultz these look good, just a couple of suggestions:

1. Please add pin-1 marker on Silkscreen
1. A pin-1 marker on F.Fab would be useful also
1. Placement origin should match the origin specified in the datasheet. 

screenshot from 2017-07-25 21-45-45

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks for taking a look.
1. KLC 7.3.vi says "where appropriate" and since these footprints can obviously only go in one way I thought this wasn't necessary. Please confirm.
2. Makes sense. I only see one example from a USB conn with a little chevron; would that be OK?
image
3. I think it is. The in the horizontal this is on the CL (center line), but see how all vertical dimensions are coming from the bottom of the keepout marked "FRONT EDGE OF PCB"? Where you marked is the centerline of the THTs, but not the origin of the part. Or am I missing something?

Perhaps this merge should wait until https://github.com/KiCad/kicad-library/issues/1443#issuecomment-317870441 is settled, since it looks like that will drive a change as well?

**Comment by SchrodingersGat** [comment]
1. Pin-1 indication is also helpful if you are debugging a circuit - so you know which pin to probe!
1. Chevron looks fine to me :)
1. My reading of the datasheet shows a clear origin cross (which I have overlaid with red). I think this is independent of all the y-measurements being made from the edge (that's just a handy reference point). The point of the origin is so that the pick and place machine knows where to place the component on the board. It makes it simpler for board loading if the part origin matches what the manufacturer is expecting based on how the part is loaded in the reel.

**Comment by poeschlr** [comment]
For the pin 1 marker on fab you can also take a look at the recently added display footprints.
There we used the 4 sided chip array marker from the following picture.
Polarity

From pull request https://github.com/KiCad/Displays.pretty/pull/10#issuecomment-312220951
screenshot from 2017-06-30 11-21-13

**Comment by evanshultz** [comment]
Thanks for the comments.

@SchrodingersGat OK. for debugging it makes sense.

@poeschlr I like this suggestion so that the fab lines stay under the part and have less chance to crash with another footprint.

If the first two items are OK below I'll move the origin and update all footprints:
image

(The ref des is back to the old position here, but don't worry about that.)

**Comment by evanshultz** [comment]
[And, should we wait for the dust to settle on keepouts or has enough feedback been gathered already?](https://github.com/KiCad/kicad-library/issues/1443#issuecomment-318074955)

**Comment by evanshultz** [comment]
OK. Made the requested updates:
- Added pin 1 mark in silk
- Added pin mark in fab
- Moved part origin inline with pads
- Changed keepout to Dwgs.User with text note

Only KLC violation is that the footprint isn't at the calculated origin, but we discussed that above.

New image:
image

@SchrodingersGat 
Can you review? Reminder that the HDMI library needs to be added once these are merged.

**Comment by SchrodingersGat** [comment]
The description for the keepout layer should be on the **Comments** layer, not the **Drawings** layer.

**Comment by evanshultz** [comment]
@SchrodingersGat 
Oops. Thanks for correcting me. They're updated.

**Comment by SchrodingersGat** [comment]
Thanks! I think the recent updates have made a large improvement. Thanks for submitting these. I will open a PR to add the HDMI library.

**Comment by SchrodingersGat** [comment]
[PR is here](https://github.com/KiCad/kicad-library/pull/1476)

**Pull request merged**
